config/routes.rb
Rails.application.routes.draw do
  root 'cms/services#index'
  namespace :api do
    api_version(
      module: 'V1',
      header: { name: 'Accept', value: 'application/vnd.servicesmanager.v1+json' },
      default: true
    ) do
      resources :users, only: :show
      resources :services, only: :show
    end
  end

  namespace :cms do
    resources :users
    resources :services, only: [:index, :edit, :update]
    controller :sessions do
      get '/login' => :new
      post '/login' => :create
      delete '/logout' => :destroy
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users

  def decorated_name
    name.humanize
  end
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :admin, -> { user_admin }, class_name: 'User', foreign_key: 'user_id'

  has_many :user_services, dependent: :destroy
  has_many :users, -> { user }, through: :user_services

  mount_uploader :logo, LogoUploader
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  has_secure_password

  alias_attribute :password_digest, :encrypted_password
  validates :email, presence: true,
                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password, presence: true,
                       confirmation: true

  belongs_to :role
  has_many :user_services, dependent: :destroy
  has_many :services, through: :user_services

  has_many :managed_services, foreign_key: 'user_id', class_name: 'Service'

  scope :user_admin, -> { where(role: Role.find_by(name: 'user_admin')) }
  scope :user,       -> { where(role: Role.find_by(name: 'user')) }

  mount_uploader :avatar, AvatarUploader

  def password
    @password ||= BCrypt::Password.new(encrypted_password)
  end

  def password=(new_password)
    @password = BCrypt::Password.create(new_password)
    self.encrypted_password = @password
  end

  def name_with_position
    "#{full_name} | #{position}"
  end

  def own_services
    if self.is_user_admin?
      managed_services
    elsif self.is_user?
      services
    end
  end

  def method_missing(method_name, *args, &block)
    if match = role_check(method_name)
      role.name == match[1]
    else
      super
    end
  end

  def role_check(role)
    /^is?_([a-zA-Z_]*)\?$/.match(role)
  end
end

app/models/user_service.rb
class UserService < ApplicationRecord
  belongs_to :user
  belongs_to :service
end

app/controllers/api/v1/base_controller.rb
module Api
  module V1
    class BaseController < ::ApplicationController
      protect_from_forgery with: :null_session
    end
  end
end

app/controllers/api/v1/services_controller.rb
module Api
  module V1
    class ServicesController < BaseController
      def show
        @service = Service.find(params[:id])
        render json: @service
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < BaseController
      def show
        @user = User.find(params[:id])
        render json: @user
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def record_not_found(error)
    render json: { error: error.to_s }, status: :not_found
  end
end

app/controllers/cms/base_controller.rb
module Cms
  class BaseController < ::ApplicationController
    protect_from_forgery with: :exception
    before_action :verify_authenticity_token
    prepend_before_action :authenticate!

    helper_method :warden, :signed_in?, :current_user

    def record_not_found(error)
      flash[:alert] = error.to_s
      redirect_back(fallback_location: root_path)
    end

    def signed_in?
      current_user.present?
    end

    def current_user
      warden.user
    end

    def authenticate!
      warden.authenticate!
    end

    def authorize!
      return if current_user.is_super_admin?
      flash[:alert] = I18n.t('errors.messages.unauthorized')
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/cms/services_controller.rb
module Cms
  class ServicesController < BaseController
    before_action :authorize!, except: :index, if: -> { current_user.is_user? }

    def index
      @services= current_user.is_super_admin? ? Service.all : current_user.own_services
    end

    def edit
      @service = Service.find(params[:id])
    end

    def update
      @service = Service.find(params[:id])
      if @service.update_attributes(service_params)
        redirect_to cms_services_url
      else
        render 'edit'
      end
    end

    private

    def service_params
      params.require(:service).permit(:user_id, user_ids: [])
    end
  end
end

app/controllers/cms/sessions_controller.rb
module Cms
  class SessionsController < BaseController
    skip_before_action :authenticate!, only: :new

    def new
    end

    def create
      if current_user.is_user?
        redirect_to cms_services_url
      else
        redirect_to cms_users_url
      end
    end

    def destroy
      warden.logout
      redirect_to cms_login_url
    end
  end
end

app/controllers/cms/unauthorized_controller.rb
module Cms
  class UnauthorizedController < BaseController
    skip_before_action :authenticate!

    def unauthenticated
      message = warden.message[:message] unless warden.message.nil?
      message ||= I18n.t('strategies.credentials.blank')
      respond_to do |format|
        format.html {
          flash[:alert] = message
          redirect_to cms_login_url
        }
        format.json {
          render json: { error: message }, status: :unauthorized
        }
      end
    end
  end
end

app/controllers/cms/users_controller.rb
module Cms
  class UsersController < BaseController
    before_action do
      authorize! if current_user.is_user? ||
                    current_user.is_user_admin? && ['edit', 'destroy'].include?(action_name)
    end

    def index
      @users = User.all
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        flash[:notice] = t('user.create.success')
        redirect_to cms_users_url
      else
        flash[:alert] = @user.errors.full_messages.uniq
        @reset_user = User.new(user_params.except(:email, :password_confirmation))
        render new_cms_user_path(@reset_user)
      end
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to cms_users_url
      else
        render 'edit'
      end
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to cms_users_url
    end

    private

    def user_params
      params.require(:user)
            .permit(:email, :password, :password_confirmation, :avatar, :full_name, :position, :role_id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cms/services/edit.html.erb
<h1>Add users to service</h1>

<%= form_for @service, url: { action: "update" }, html: { multipart: true } do |f| %>
  <% if current_user.is_super_admin? %>
    <div class="row">
      Admin User: <%= f.collection_select :user_id, User.user_admin, :id, :name_with_position %>
    </div>
  <% end %>
  <div class="row">
    Users:
    <%= f.collection_check_boxes :user_ids, User.user, :id, :name_with_position do |c|%>
      <div class="row">
        <%= c.check_box + c.text %>
      </div>
    <% end %>
  </div>
  <%= f.submit "Submit" %>
<% end %>

app/views/cms/services/index.html.erb
<h1>Services list</h1>

<table class="table table-hover">
  <tr>
    <th>#</th>
    <th>Logo</th>
    <th>Name</th>
    <th>Link</th>
    <th>Admin User</th>
    <th></th>
  </tr>

  <% @services.each_with_index do |service, index| %>
    <tr>
      <td><%= index+1 %></td>
      <td><%= image_tag(service.logo_url(:thumb)) if service.logo? %></td>
      <td><%= service.name %></td>
      <td><%= service.link %></td>
      <td><%= service.admin.full_name if service.admin %></td>
      <td><%= link_to "Add users", edit_cms_service_path(service) %></td>
    </tr>
  <% end %>
</table>

app/views/cms/users/edit.html.erb
<h1>Add new user</h1>

<%= form_for @user, url: { action: "update" }, html: { multipart: true } do |f| %>
  Avatar: <%= f.file_field :avatar %>
  <%= image_tag(@user.avatar_url(:thumb)) if @user.avatar? %>
  Full name: <%= f.text_field :full_name %>
  Position: <%= f.text_field :position %>
  Email: <%= f.text_field :email %>
  <% if current_user.is_super_admin? %>
    Role: <%= f.collection_select :role_id, Role.all, :id, :decorated_name %>
  <% end %>
  <%= f.hidden_field :avatar_cache %>
  <%= f.submit "Submit" %>
<% end %>

app/views/cms/users/index.html.erb
<h1>Users list</h1>

<table class="table table-hover">
  <tr>
    <th>#</th>
    <th>Avatar</th>
    <th>Full name</th>
    <th>Position</th>
    <th>Email</th>
    <th>Role</th>
    <th>Actions</th>
    <th></th>
  </tr>

  <% @users.each_with_index do |user, index| %>
    <tr>
      <td><%= index+1 %></td>
      <td><%= image_tag(user.avatar_url(:thumb)) if user.avatar? %></td>
      <td><%= user.full_name %></td>
      <td><%= user.position %></td>
      <td><%= user.email %></td>
      <td><%= user.role.decorated_name if user.role %></td>
      <td><%= link_to "Edit", edit_cms_user_path(user) %></td>
      <td><%= link_to "Delete", cms_user_path(user), data: { confirm: "Are you sure you want to delete this user?" }, method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/cms/users/new.html.erb
<h1>Add new user</h1>

<%= form_for @user, url: { action: "create" } do |f| %>

  Avatar: <%= f.file_field :avatar %>
  Full name: <%= f.text_field :full_name %>
  Position: <%= f.text_field :position %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password confirmation: <%= f.password_field :password_confirmation %>
  Role: <%= f.collection_select :role_id, Role.all, :id, :decorated_name %>
  <%= f.submit "Submit" %>

<% end %>

app/views/layouts/_common_header.html.erb
<%= link_to "Users", cms_users_path %>
<%= link_to "Services", cms_services_path %>
<%= link_to "Add new user", new_cms_user_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationTestWork</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <% if current_user && !current_user.is_user? %>
          <%= render partial: 'layouts/common_header'%>
        <% end %>
        <% if signed_in? %>
          <%= link_to "Logout", cms_logout_path, method: :delete %>
        <% end %>
      </div>
    </nav>
    <div class="container">
      <div class="row" style="margin-top: 20%">
        <div class="col-sm-6 col-sm-offset-3" >
          <% if notice %>
              <div class="alert alert-info" role="alert">
                <%= notice %>
              </div>
          <% end %>

          <% if alert %>
              <div class="alert alert-danger" role="alert">
                <%= alert %>
              </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>